name: CI-test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest
        # Service containers to run with 'container-job'
        services:
            # Label used to access the service container
            postgres:
                # Docker hub image
                image: postgres:17-alpine
                # Provide the password for postgres
                env:
                    POSTGRES_USER: root
                    POSTGRES_DB: simple_bank
                    POSTGRES_PASSWORD: secret
                # Set health check to wait until postgres17 has started
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
                # Ports to expose from the service container
                ports:
                    - 5432:5432 

        steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: ^1.24.0

        - name: Install golang-migrate
          run: |
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
            sudo mv migrate /usr/local/bin
            which migrate

        - name: Install dependencies
          run: go mod tidy

        - name: Run migrations
          run: make migrateup

        - name: Run tests
          run: make test